### ISSUE TITLE
Crashes with 1.20.6

### ISSUE THREAD

**Issue by brunociria** [jewtvet/elytrahud#3]
### **Here's the crash report:**

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-05-27 19:23:46
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_329 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_310.<init>(class_310.java:646)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 9 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method render(Lnet/minecraft/class_332;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in elytrahud.mixins.json:InGameHudMixin from mod elytrahud failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap elytrahud-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_310.<init>(class_310.java:646)

### **Mod List:**
 c2me-fabric-mc1.20.6-0.2.0+alpha.11.95.jar
 cardinal-components-api-6.0.0-rc1.jar
 Chunky-1.4.10.jar
 cicada-lib-0.7.2+1.20.5-and-above.jar
 cloth-config-14.0.126-fabric.jar
 DistantHorizons-fabric-2.0.4-a-dev-1.20.6.jar
 do_a_barrel_roll-fabric-3.6.0+1.20.6.jar
 dynamic-fps-3.4.3+minecraft-1.20.5-fabric.jar
 **elytrahud-1.0.2.jar**
 entityculling-fabric-1.6.5-mc1.20.6.jar
 fabric-api-0.99.0+1.20.6.jar
 ferritecore-6.1.1-fabric.jar
 flightassistant-2.2.0+mc1.20.6.jar
 ImmediatelyFast-Fabric-1.2.15+1.20.6.jar
 indium-1.0.30+mc1.20.4.jar
 iris-1.7.0+mc1.20.6.jar
 krypton-0.2.7.jar
 lazydfu-0.1.3.jar
 lithium-fabric-mc1.20.6-0.12.3.jar
 memoryleakfix-fabric-1.17+-1.1.5.jar
 modernfix-fabric-5.17.3+mc1.20.6.jar
 modmenu-10.0.0-beta.1.jar
 noisium-fabric-2.1.0+mc1.20.5-1.20.6.jar
 reeses_sodium_options-1.7.2+mc1.20.5-build.103.jar
 servercore-fabric-1.5.2+1.20.6.jar
 sodium-extra-0.5.5+mc1.20.6-build.118.jar
 sodium-fabric-0.5.8+mc1.20.6.jar
 tectonic-fabric-1.20.5-2.3.4.jar
 Terralith_1.20_v2.5.1.jar
 threadtweak-fabric-1.20.6-0.1.3.jar
 YetAnotherConfigLib-3.4.4+1.20.6-fabric.jar

**Comment by jewtvet** [comment]
thanks, as I see Mojang changed something in 1.20.6, I will fix it in 1-2 days
