### ISSUE TITLE
Crashes with fabric 1.21.3

### ISSUE THREAD

**Issue by linuces04** [jewtvet/elytrahud#6]
Whenever I try to use this with fabric 1.21.3, it just crashes the game. A fix would be greatly appreciated :)

crash report:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-11-30 16:10:20
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/class_1770
	at knot//jewtvet.elytrahud.HudData.update(HudData.java:41)
	at knot//jewtvet.elytrahud.Common.lambda$onInitializeClient$1(Common.java:53)
	at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:63)
	at knot//net.minecraft.class_638.handler$zhg000$fabric-lifecycle-events-v1$tickWorldAfterBlockEntities(class_638.java:1106)
	at knot//net.minecraft.class_638.method_18116(class_638.java:264)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1888)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1770
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//jewtvet.elytrahud.HudData.update(HudData.java:41)
	at knot//jewtvet.elytrahud.Common.lambda$onInitializeClient$1(Common.java:53)
	at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:63)
	at knot//net.minecraft.class_638.handler$zhg000$fabric-lifecycle-events-v1$tickWorldAfterBlockEntities(class_638.java:1106)
	at knot//net.minecraft.class_638.method_18116(class_638.java:264)

-- Uptime --
Details:
	JVM uptime: 75.023s
	Wall uptime: 59.887s
	High-res time: 53.854s
	Client ticks: 952 ticks / 47.600s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:957)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Linuces09'/21930, l='ClientLevel', x=191.90, y=151.20, z=-58.62]]
	Chunk stats: 729, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 18913309 game time, 546837 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
	Tracked entity count: 158

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, autoclicker, chat_heads, cicada, cloth-config, do_a_barrel_roll, elytrahud, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, modmenu, sodium, xaerominimap, xaeroworldmap, yet_another_config_lib_v3, file/VanillaTweaks_r546038_MC1.21.x, file/STM[Clear Vision Plus][5.0][1.21.2-1.21.3]

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 121403048 bytes (115 MiB) / 671088640 bytes (640 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5625U with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon (TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.12026.8002
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: Unknown
	Virtual memory max (MiB): 31362.13
	Virtual memory used (MiB): 15484.04
	Swap memory total (MiB): 15681.07
	Swap memory used (MiB): 547.28
	Space in storage for jna.tmpdir (MiB): available: 34864.85, total: 241128.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 34864.85, total: 241128.00
	Space in storage for io.netty.native.workdir (MiB): available: 34864.85, total: 241128.00
	Space in storage for java.io.tmpdir (MiB): available: 34864.85, total: 241128.00
	Space in storage for workdir (MiB): available: 34864.85, total: 241128.00
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		autoclicker: Auto Clicker 21.1.0
		chat_heads: Chat Heads 0.13.6
		cicada: CICADA 0.9.1+1.21.2-and-above
		cloth-config: Cloth Config v16 16.0.141
			cloth-basic-math: cloth-basic-math 0.6.1
		do_a_barrel_roll: Do a Barrel Roll 3.8.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.2-beta.4
		elytrahud: ElytraHud (MFS 2020) 1.1.0
		fabric-api: Fabric API 0.106.1+1.21.3
			fabric-api-base: Fabric API Base 0.4.48+2127dc7240
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.78+c47b9d4340
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.5+c47b9d4340
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+c47b9d4340
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+c47b9d4340
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.2+c47b9d4340
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.22+c47b9d4340
			fabric-command-api-v1: Fabric Command API (v1) 1.2.56+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.35+c47b9d4340
			fabric-commands-v0: Fabric Commands (v0) 0.2.73+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.5+c47b9d4340
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.0+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.0+c47b9d4340
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+c47b9d4340
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.38+c47b9d4340
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.14+c47b9d4340
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+c47b9d4340
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.5+c47b9d4340
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.9+c47b9d4340
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4340
			fabric-item-api-v1: Fabric Item API (v1) 11.1.5+c47b9d4340
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.15+e7c9ab6640
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+c47b9d4340
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.22+c47b9d4340
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.24+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.12+c47b9d4340
			fabric-message-api-v1: Fabric Message API (v1) 6.0.19+c47b9d4340
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.7+c47b9d4340
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.3+56ec7ac640
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.7+c47b9d4340
			fabric-particles-v1: Fabric Particles (v1) 4.0.8+c47b9d4340
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.2+c47b9d4340
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+56ec7ac640
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.3+c47b9d4340
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.3+c47b9d4340
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.13+c47b9d4340
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.81+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.5+c47b9d4340
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+c47b9d4340
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.5+c47b9d4340
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.32+c47b9d4340
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.98+c47b9d4340
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+c47b9d4340
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.0+c47b9d4340
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+c47b9d4340
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		gammautils: Gamma Utils 2.2.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.3
		modmenu: Mod Menu 12.0.0-beta.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		sodium: Sodium 0.6.0-beta.3+mc1.21.2
		xaerominimap: Xaero's Minimap 24.6.2
		xaeroworldmap: Xaero's World Map 1.39.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21.2-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: fabric-loader-0.16.7-1.21.3
	Launcher name: java-minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon (TM) Graphics GL version 3.2.0 Core Profile Context 22.20.26.08.221227, ATI Technologies Inc.
	Window size: 1920x1009
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 10/12 chunks
	Resource Packs: vanilla, fabric, autoclicker, chat_heads, cicada, cloth-config, do_a_barrel_roll (incompatible), elytrahud, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, modmenu, sodium, xaerominimap (incompatible), xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible), file/VanillaTweaks_r546038_MC1.21.x (incompatible), file/STM[Clear Vision Plus][5.0][1.21.2-1.21.3]
	Current Language: en_us
	Locale: en_AU
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 5625U with Radeon Graphics

**Comment by badger1505** [comment]
Similar issue - as soon as Elytra is "activated" in flight mode (not just worn, but is active in flight), Minecraft crashes.  

Crash Log:
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-12-26 18:54:56
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/class_1770
	at knot//jewtvet.elytrahud.HudData.update(HudData.java:41)
	at knot//jewtvet.elytrahud.Common.lambda$onInitializeClient$1(Common.java:53)
	at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:63)
	at knot//net.minecraft.class_638.handler$zfk000$fabric-lifecycle-events-v1$tickWorldAfterBlockEntities(class_638.java:1106)
	at knot//net.minecraft.class_638.method_18116(class_638.java:264)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1888)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1770
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//jewtvet.elytrahud.HudData.update(HudData.java:41)
	at knot//jewtvet.elytrahud.Common.lambda$onInitializeClient$1(Common.java:53)
	at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:63)
	at knot//net.minecraft.class_638.handler$zfk000$fabric-lifecycle-events-v1$tickWorldAfterBlockEntities(class_638.java:1106)
	at knot//net.minecraft.class_638.method_18116(class_638.java:264)

-- Uptime --
Details:
	JVM uptime: 599.636s
	Wall uptime: 592.506s
	High-res time: 591.596s
	Client ticks: 11726 ticks / 586.300s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:957)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Badger1505'/19, l='ClientLevel', x=-424.90, y=114.14, z=-310.20]]
	Chunk stats: 5041, 3653
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,79,-96), Section: (at 0,15,0 in -5,4,-6; chunk contains blocks -80,-64,-96 to -65,319,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 14098 game time, 14098 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 161

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, advanced-xray-fabric, cloth-config, elytrahud, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, journeymap, modmenu

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 581771112 bytes (554 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13600K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: Raptor Lake
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6636
	Graphics card #1 name: Intel(R) UHD Graphics 770
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 1024.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.101.4577
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 34578.82
	Virtual memory used (MiB): 19937.72
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 129.64
	Space in storage for jna.tmpdir (MiB): available: 309378.59, total: 953068.56
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 309378.59, total: 953068.56
	Space in storage for io.netty.native.workdir (MiB): available: 309378.59, total: 953068.56
	Space in storage for java.io.tmpdir (MiB): available: 309378.59, total: 953068.56
	Space in storage for workdir (MiB): available: 309378.59, total: 953068.56
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 21.2.0
		cloth-config: Cloth Config v16 16.0.141
			cloth-basic-math: cloth-basic-math 0.6.1
		elytrahud: ElytraHud (MFS 2020) 1.1.0
		fabric-api: Fabric API 0.109.0+1.21.3
			fabric-api-base: Fabric API Base 0.4.50+119c825640
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.81+fd37071f40
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+fd37071f40
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+fd37071f40
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+fd37071f40
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.4+fd37071f40
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.24+fd37071f40
			fabric-command-api-v1: Fabric Command API (v1) 1.2.58+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.37+c9d82ab240
			fabric-commands-v0: Fabric Commands (v0) 0.2.75+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.8+fd37071f40
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.3+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.3+84ebbb0e40
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+fd37071f40
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+dbad41f140
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.17+fd37071f40
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+fd37071f40
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.8+825023f840
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.12+c2c3ac4740
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+fd37071f40
			fabric-item-api-v1: Fabric Item API (v1) 11.1.7+fd37071f40
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.17+fd37071f40
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+fd37071f40
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.1+6da5ef6940
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.26+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.14+fd37071f40
			fabric-message-api-v1: Fabric Message API (v1) 6.0.21+fd37071f40
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.9+fd37071f40
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.5+fd37071f40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.9+fd37071f40
			fabric-particles-v1: Fabric Particles (v1) 4.0.10+fd37071f40
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.4+fd37071f40
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.2+fd37071f40
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.5+fd37071f40
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.5+fd37071f40
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.15+fd37071f40
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.83+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.7+fd37071f40
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+fd37071f40
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+fd37071f40
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.34+fd37071f40
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.100+fd37071f40
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+fd37071f40
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.3+fd37071f40
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+fd37071f40
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		journeymap: Journeymap 1.21.3-6.0.0-beta.31
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.17-1.21.3
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21.3-SNAPSHOT
		minecraft: Minecraft 1.21.3
		modmenu: Mod Menu 12.0.0-beta.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
	Launched Version: fabric-loader-0.16.9-1.21.3
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.36, NVIDIA Corporation
	Window size: 2560x1440
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 32/32 chunks
	Resource Packs: vanilla, fabric, advanced-xray-fabric, cloth-config, elytrahud, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, journeymap, modmenu
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 20x 13th Gen Intel(R) Core(TM) i5-13600K
	Server Running: true
	Player Count: 1 / 8; [class_3222['Badger1505'/19, l='ServerLevel[New World]', x=-424.90, y=114.14, z=-310.20]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: fabric, fabric-convention-tags-v2, minecart_improvements, redstone_experiments, trade_rebalance, vanilla, winter_drop
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 7812090024439431780
	Suppressed Exceptions: ~~NONE~~


Minecraft Error Message: 
The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: net/minecraft/class_1770

Minecraft Exit Code: -1

**Comment by jewtvet** [comment]
The mod doesnt support 1.21.3 and 1.21.4 right now. Im going to update all of my mods in a week, sorry for that

**Comment by badger1505** [comment]
> The mod doesnt support 1.21.3 and 1.21.4 right now. Im going to update all of my mods in a week, sorry for that

Thank you!  Looking forward to it!
