### ISSUE TITLE
Request for 1.21.4 update

### ISSUE THREAD

**Issue by Kishku7** [jewtvet/elytrahud#7]
Your loyal follower is back asking for another update.

[11:11:03] [Render thread/ERROR]:
Unreported exception thrown!
java.lang.NoClassDefFoundError: net/minecraft/class_1770
at knot/jewtvet.elytrahud.HudData.update(HudData.java:41) ~[elytrahud-1.1.0.jar:?]
at knot/jewtvet.elytrahud.Common.lambda$onInitializeClient$1(Common.java:53) ~[elytrahud-1.1.0.jar:?]
at knot/net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.5.4+bf2a60eb04-b4ff52bc5028a975.jar:?]
at knot//MC/net.minecraft.client.world.ClientWorld.handler$blh000$fabric-lifecycle-events-v1$tickWorldAfterBlockEntities(ClientWorld.java:3628) ~[client-intermediary.jar:?]
at knot//MC/net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld.java:268) ~[client-intermediary.jar:?]
at knot//MC/net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1879) ~[client-intermediary.jar:?]
at knot//MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1302) ~[client-intermediary.jar:?]
at knot//MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:922) [client-intermediary.jar:?]
at knot/net.minecraft.client.main.Main.main(Main.java:267) [client-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1770
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
... 12 more

**Comment by jewtvet** [comment]
Ok, i will update it in a week

**Comment by ArduFish** [comment]
@jewtvet please update it.

**Comment by superbomb404** [comment]
pls
